{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mxmmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mxmmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mxmmod/mxmmod_{{ version }}.tar.gz
  sha256: b877024a2d738ea5c583c78875d1874e40b6d80f76f37d7baa7bac6789379574

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-openmx
  run:
    - r-base
    - r-openmx

test:
  commands:
    - $R -e "library('mxmmod')"           # [not win]
    - "\"%R%\" -e \"library('mxmmod')\""  # [win]

about:
  home: https://github.com/khusmann/mxmmod
  license: Apache-2.0
  summary: Provides a convenient interface in 'OpenMx' for building Estabrook's (2015) <doi:10.1037/a0034523> Measurement Model of Derivatives (MMOD).
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann

# Package: mxmmod
# Type: Package
# Title: Measurement Model of Derivatives in 'OpenMx'
# Version: 1.0.1
# Authors@R: c( person( given = 'Kyle D.', family = 'Husmann', role = c('aut', 'cre'), email = 'kdh38@psu.edu' ), person(given = 'Timothy R.', family = 'Brick', role = c('aut'), email = 'tbrick@psu.edu' ), person(given = 'Ryne', family = 'Estabrook', role = c('aut'), email = 'cestabr2@uic.edu' ) )
# Description: Provides a convenient interface in 'OpenMx' for building Estabrook's (2015) <doi:10.1037/a0034523> Measurement Model of Derivatives (MMOD).
# License: Apache License 2.0
# Encoding: UTF-8
# LazyData: true
# Imports: OpenMx
# Suggests: knitr, rmarkdown, testthat, tidyverse
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# NeedsCompilation: no
# Packaged: 2020-03-26 20:56:45 UTC; khusmann
# Author: Kyle D. Husmann [aut, cre], Timothy R. Brick [aut], Ryne Estabrook [aut]
# Maintainer: Kyle D. Husmann <kdh38@psu.edu>
# Repository: CRAN
# Date/Publication: 2020-03-28 14:50:05 UTC
